version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Replace with your preferred root password
      MYSQL_DATABASE: django_db          # Replace with your database name
      MYSQL_USER: django_user            # Replace with your database username
      MYSQL_PASSWORD: django_password    # Replace with your database password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
